add pipe operator
oxalica/nil pull request #152
Opened 2024-09-14 17:06 UTC by q60

> it works but help needed, i'm in love/hate relationships with tree-sitter specifically and parsers in general

#### before

![image](https://github.com/user-attachments/assets/94572222-1c9b-4403-8377-acf5c07dc708)

#### after

![image](https://github.com/user-attachments/assets/cb2e7a8b-c116-4dae-9e08-01740dcfb9ad)

2024-09-16 20:53 UTC, eclairevoyant commented
It's a ggod start, but this misses support for the `<|` operator

2024-09-16 23:00 UTC, oxalica requested changes
Thanks, I just know that Nix got new experimental operators. It may worth referencing the source PR https://github.com/NixOS/nix/pull/11131 

CI failure is unrelated and is already fixed on `main`. A rebase should fix it.

2024-09-16 23:00 UTC, oxalica commented on crates/ide/src/ide/syntax_highlighting.rs
> -            T![++] | T!["//"] => HlTag::Operator(HlOperator::Aggregation),
It's not a collection operator. It may need another `HlOperator` variant like `Pipe`.

2024-09-16 23:00 UTC, oxalica commented on crates/ide/src/ty/infer.rs
> +                    BinaryOpKind::Concat | BinaryOpKind::Pipe => {
We shouldn't unity arguments of pipe operators to be List. 
They should follow the handling of [`Expr::Apply`](https://github.com/oxalica/nil/blob/555d517d46f0901988d752c7bbebccbf66b74f91/crates/ide/src/ty/infer.rs#L273) with two arguments flipped.

2024-09-16 23:00 UTC, oxalica commented on crates/syntax/src/kind.rs
> +    PIPE = [|>],
```suggestion
    OR_GT = [|>],
```

Here we name symbols syntactically, not semantically.

2024-09-16 23:00 UTC, oxalica commented on crates/syntax/src/parser.rs
> +            T![|>] => (21, 22),
This precedence is incorrect. [According to Nix](https://github.com/NixOS/nix/blob/e086d5d899aaefdce8cc7a509cb2971be9732b2b/doc/manual/src/language/operators.md#operators), it should have a lower precedence than logic-imply `->`. So it should goes above to be `(-1, 0)`, which underflows `u8`... Unfortunately, we need to shift all other BP values up by `+10` (for simplicity and more future proof), so `|>` becomes `(9, 10)`, `->` becomes `(12, 11)`, and etc.

2024-09-17 19:09 UTC, q60 commented on crates/ide/src/ty/infer.rs
> +                    BinaryOpKind::Concat | BinaryOpKind::Pipe => {
i don't quite follow this, need an example... speaking of the other threads, i can make the changes and push them right away
that's quite dumb, but i have basically zero experience in parsers :skull: 
this PR (plus patches in `tree-sitter-nix`, `rnix-parser` and `alejandra`) emerged from my need of using pipe operator w/o errors from the language server and with working formatter. then i showed all of this to friends and they kinda expected me to make PRs to the base repos :skull: :skull: :skull: 
btw i also opened a PR in `tree-sitter-nix`, but considering the status quo of `rnix-parser` and it being a dependency of `alejandra`, i am totally unsure how to work this out :sob: 
sorry for this silly venting in this thread

2024-11-14 09:10 UTC, viperML commented
I hate to be that one that writes "any progress on this?", but I need to be that one

2024-11-19 21:51 UTC, closed without merging