add emacs-lsp integration example
oxalica/nil pull request #37
Opened 2022-11-27 13:50 UTC by Mic92

2022-11-27 16:46 UTC, oxalica requested changes
Could you also add an example for LSP configurations?

2022-11-27 16:46 UTC, oxalica commented on README.md
> +``` jsonc
This is definitely not `jsonc`.

2022-11-27 21:26 UTC, Mic92 commented
What do you mean by `LSP configurations`? The configuration was all it needed to get it running for me.

2022-11-28 07:30 UTC, oxalica commented
> What do you mean by `examples for LSP configurations`? The configuration was all it needed to get it running for me.

Not just "get it running". There are some configuration options of the server, like formatting command. Usually LSP clients have a way to pass these configurations to the server.

To reduce questions like "why formatting is not working", I included the way to set these configurations for editors/plugins that I'm familiar with, like `coc.nvim` in the README https://github.com/oxalica/nil#vimneovim-with-cocnvim

2022-11-28 12:28 UTC, Mic92 commented
Maybe someone else can take this one over. I don't want to dig too deep into fiddling with emacs-lsp configuration and just wait for the next release to end up in doom-emacs so it just works out-of-the-box.

2022-11-28 12:28 UTC, closed without merging