Diagnostics CLI: return different exit code when only warnings
oxalica/nil pull request #90
Opened 2023-06-07 12:01 UTC by tennox

Would love to be able to ignore warnings for the [pre-commit hook in my devenv](https://github.com/cachix/pre-commit-hooks.nix/blob/master/modules/hooks.nix#L774)

2023-06-09 14:26 UTC, oxalica requested changes

2023-06-09 14:26 UTC, oxalica commented on crates/nil/src/main.rs
> +        Ok(diags.iter().map(|diag| diag.severity())/*.unique()*/.collect())
We could sort `Severity` in [definition](https://github.com/oxalica/nil/blob/dcd38b96c91a2d07552f824a6480e00dc7b4948a/crates/ide/src/diagnostic.rs#L38) from mildest to severest and `derive(Ord)`. Then we can just:

```suggestion
        Ok(diags.iter().map(|diag| diag.severity()).max())
```

2023-06-09 14:26 UTC, oxalica commented on crates/nil/src/main.rs
> +            if severities.is_empty() {
To me, warnings should not be errors. We can just change the default behavior here to make it returns non-zero only on errors. Users who want the old deny-all behavior can still check if stdout is empty anyway. What do you think?

2023-06-09 16:21 UTC, tennox commented on crates/nil/src/main.rs
> +        Ok(diags.iter().map(|diag| diag.severity())/*.unique()*/.collect())
Done :+1:

2023-06-09 16:22 UTC, tennox commented on crates/nil/src/main.rs
> +            if severities.is_empty() {
Agreed, checked [eslint for comparison](https://eslint.org/docs/latest/use/command-line-interface#exit-codes):

>     0: Linting was successful and there are no linting errors. If the [--max-warnings](https://eslint.org/docs/latest/use/command-line-interface#--max-warnings) flag is set to n, the number of linting warnings is at most n.
>     1: Linting was successful and there is at least one linting error, or there are more linting warnings than allowed by the --max-warnings option.
>     2: Linting was unsuccessful due to a configuration problem or an internal error.

I felt `--max-warnings` weird, so i decided for a simple `--error-on-warnings` and implemented it as in your suggestion as a breaking change :tipping_hand_man:  :+1:

2023-06-09 19:48 UTC, oxalica commented on docs/features.md
> +  Exit with non-zero code if there are any diagnostics. (`1` for errors, `2` if only warnings)
This is outdated.

2023-06-09 19:48 UTC, oxalica commented on crates/nil/src/main.rs
> +            if severities.is_empty() {
> I felt `--max-warnings` weird,

I don't like it either. I prefer rust's `--{allow,warn,deny} {LINT,warnings}` approach which also supports promoting, ignoring and filtering. With that customization support, we can simply stick on just exit on errors. But we don't need to implement these flags in this PR, whose main goal is to loosen the exit code for warnings. You can leave these flags to me later.

> as in your suggestion as a breaking change

I don't consider accepting more code a breaking change.

2023-06-09 19:50 UTC, oxalica requested changes
Also please squash and edit your commit messages to comply to the main branch.

2023-06-10 10:19 UTC, tennox commented
Okay, I did the requested changes & hope the squashed commit message is good enough :sweat_smile:

2023-06-11 22:31 UTC, merged

2023-06-11 22:31 UTC, oxalica commented
Thanks!